name: Move TRANS_HYPE Files to Root

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행
  pull_request: # PR 생성 시 실행

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move files from TRANS_HYPE to root
        run: |
          mv TRANS_HYPE/* .
          rm -rf TRANS_HYPE  # 폴더 삭제

      - name: Verify moved files
        run: ls -la # 파일 이동 확인

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "jian-nam"
          git config --global user.email "jeeahn2929@gmail.com"

          git checkout -b dist || git checkout dist
          git add .
          git commit -m "Moved files from TRANS_HYPE to root"
          git push origin dist
